version: "3.2"
services:
  
  app:
    build: .
    image: "sdemurin/audeeo:0.0.1"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /srv/audeeo/app
      - ./config.py:/srv/audeeo/config.py
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://admin:${POSTGRES_PASSWORD}@db/podcast"
      APP_SETTINGS: "config.DevelopmentConfig"
      IA_S3_ACCESS_KEY_ID: "${IA_S3_ACCESS_KEY_ID}"
      IA_S3_SECRET_ACCESS_KEY_ID: "${IA_S3_SECRET_ACCESS_KEY_ID}"
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
      FLASK_APP: "app"
      FLASK_ENV: "development"
    command: ["flask", "run", "--host", "0.0.0.0", "--port", "8000"]
  
  db:
    image: "postgres:11.2"
    restart: always
    environment:
      POSTGRES_DB: podcast
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
