version: "3.7"
services:
  app-test:
    build: .
    depends_on:
      - db-test
    volumes:
      - ./audeeo:/srv/audeeo/audeeo
      - ./tests:/srv/audeeo/tests
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db-test/postgres"
      FLASK_SECRET_KEY: "ohphisai5lohTha"
      FLASK_TESTING: 1
    networks:
      - test
    command: ["wait-for-it", "db-test:5432", "--timeout=30", "--strict", "--",
              "flask", "test"]

  db-test:
    image: "postgres:11.2"
    networks:
      - test

networks:
  test:
    name: test
