version: "3.7"
services:
  app-test:
    build: .
    depends_on:
      - db-test
    volumes:
      - ./audeeo:/srv/audeeo/audeeo
      - ./tests:/srv/audeeo/tests
      - ./docker-entrypoint.test.sh:/srv/audeeo/docker-entrypoint.test.sh
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db-test/postgres"
      FLASK_SECRET_KEY: "ohphisai5lohTha"
      FLASK_TESTING: 1
      IA_S3_ACCESS_KEY_ID: test_key
      IA_S3_SECRET_ACCESS_KEY_ID: test_secret_key
    networks:
      - test
    entrypoint: ["wait-for-it", "db-test:5432", "--timeout=30", "--strict", "--", "./docker-entrypoint.test.sh"]

  db-test:
    image: "postgres:11.2"
    networks:
      - test

networks:
  test:
    name: test
