version: "3.2"
services:
  app:
    build: .
    image: "sdemurin/audeeo:0.0.1"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./config.py:/srv/audeeo/config.py
      - ./audeeo:/srv/audeeo/audeeo
      - ./migrations:/srv/audeeo/migrations
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      APP_SETTINGS: "config.DevelopmentConfig"
      FLASK_ENV: "development"
    command: ["wait-for-it", "db:5432", "--timeout=30", "--strict", "--",
              "flask", "run", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: "postgres:11.2"
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
