version: "3.7"
services:
  app:
    build: .
    image: "sdemurin/audeeo:latest"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./audeeo:/srv/audeeo/audeeo
      - ./migrations:/srv/audeeo/migrations
    env_file: .env
    environment:
      FLASK_ENV: "development"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    entrypoint: ["wait-for-it", "db:5432", "--timeout=30", "--strict", "--", "./docker-entrypoint.sh"]

  db:
    image: "postgres:11.2"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
