# TODO fill domain, when it's ready
defaultEntryPoints=["http", "https"]

[entryPoints]
  [entryPoints.http]
  address=":80"
    [entryPoints.http.redirect]
      entryPoint="https"
  [entryPoints.https]
  address=":443"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "%domain%"
watch = true
network = "traefik-net"

[acme]
  email="acme@%domain%"
  storage="/etc/traefik_acme/acme.json"
  entryPoint="https"
  acmeLogging=true
  OnHostRule=true
  [acme.httpChallenge]
    entryPoint = "http"

[accessLog]
