import os


DEBUG = False
TESTING = bool(os.getenv('FLASK_TESTING', False))

CSRF_ENABLED = True
SECRET_KEY = os.getenv('FLASK_SECRET_KEY')

SECURITY_PASSWORD_SALT = os.getenv('FLASK_SECRET_KEY')
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False

SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False

IA_S3_ACCESS_KEY_ID = os.getenv('IA_S3_ACCESS_KEY_ID')
IA_S3_SECRET_ACCESS_KEY_ID = os.getenv('IA_S3_SECRET_ACCESS_KEY_ID')
