"""[File] add 'created_at' field

Revision ID: 728d6a457da5
Revises: 932891bcfbd5
Create Date: 2019-03-08 10:42:50.012542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728d6a457da5'
down_revision = '932891bcfbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'created_at')
    # ### end Alembic commands ###
