"""[File] add 'pub_date' and 'file_size' fields

Revision ID: c49a60834ab1
Revises: 728d6a457da5
Create Date: 2019-03-08 16:49:17.089133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49a60834ab1'
down_revision = '728d6a457da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('pub_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'pub_date')
    op.drop_column('files', 'file_size')
    # ### end Alembic commands ###
