"""[Episode] make `title` and `url` not nullable

Revision ID: e8e7944dbe78
Revises: 4bc1ed775a6a
Create Date: 2019-04-26 11:14:02.196845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e7944dbe78'
down_revision = '4bc1ed775a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('episode', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
